theme: jekyll-theme-minimal

title: Jasmine Otto [CV](./cv single.pdf)
description: PhD student in Applied Mathematics at the University of Illinois at Chicago.

codes: Interacts
writes: Writings
draws: Creativity